name: git-confined
version: "v2.42.1"
summary: Git SCM
description: |
  Git is a fast, scalable, distributed revision control system with an unusually rich command set that provides both high-level operations and full access to internals.
  
  Git is an Open Source project covered by the GNU General Public License version 2 (some parts of it are under different licenses, compatible with the GPLv2). It was originally written by Linus Torvalds with help of a group of hackers around the net.
  
  In order to enable this Snap as your preferred git tool, run: `sudo snap alias git-confined git`
confinement: strict
base: core22
compression: lzo

architectures:
- build-on: amd64
- build-on: arm64
- build-on: armhf

apps:
  git-confined:
    environment:
      MAN_TEST_DISABLE_SYSTEM_CONFIG: 1
      MANPATH: $SNAP/usr/share/man
      GROFF_FONT_PATH: $SNAP/usr/share/groff/current/font
      GROFF_TMAC_PATH: $SNAP/usr/share/groff/current/tmac
    command: usr/bin/git
    plugs: [ home, removable-media, network, ssh-keys, ssh-public-keys ]

lint:
  ignore:
    - classic
    - library

layout:
  /etc/gitconfig:
    bind-file: $SNAP_DATA/etc/gitconfig
  /usr/libexec/git-core:
    symlink: $SNAP/usr/libexec/git-core
  /usr/share/git-core/templates:
    symlink: $SNAP/usr/share/git-core/templates
  /etc/manpath.config:
    symlink: $SNAP/etc/manpath.config
  /usr/share/locale:
    bind: $SNAP/usr/share/locale
  /usr/lib/man-db:
    bind: $SNAP/usr/lib/man-db

parts:
  git:
    source: https://github.com/git/git.git
    source-tag: v2.42.1
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-curl
      - --with-expat
    override-prime: |
      craftctl default
      cd $CRAFT_PART_BUILD
      DESTDIR=$CRAFT_PRIME make install-man
    build-packages:
      - build-essential
      - gettext
      - libssl-dev
      - libexpat1-dev
      - zlib1g-dev
      - asciidoc
      - xmlto
    stage-packages:
      - gettext
      - libcurl4-openssl-dev
      - zlib1g
      - openssh-client
      - man
      - man-db
      - groff-base
      - vim
      - nano
  wrappers:
    plugin: dump
    source: snap/local
    organize:
      '*': usr/bin/
